# GoReleaser packages the nebu CLI only. Published processor binaries are
# released independently from github.com/withObsrvr/nebu-processor-registry.
FROM gcr.io/distroless/static-debian12:nonroot

ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/nebu /usr/local/bin/nebu

WORKDIR /data
ENTRYPOINT ["/usr/local/bin/nebu"]
CMD ["--help"]
