// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: examples/processors/ledger-change-stats/proto/ledger_change_stats.proto

package changestatspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LedgerChangeStats struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	LedgerSequence          uint32                 `protobuf:"varint,1,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	LedgerEntriesCreated    uint32                 `protobuf:"varint,2,opt,name=ledger_entries_created,json=ledgerEntriesCreated,proto3" json:"ledger_entries_created,omitempty"`
	LedgerEntriesUpdated    uint32                 `protobuf:"varint,3,opt,name=ledger_entries_updated,json=ledgerEntriesUpdated,proto3" json:"ledger_entries_updated,omitempty"`
	LedgerEntriesDeleted    uint32                 `protobuf:"varint,4,opt,name=ledger_entries_deleted,json=ledgerEntriesDeleted,proto3" json:"ledger_entries_deleted,omitempty"`
	FeeRelatedChanges       uint32                 `protobuf:"varint,5,opt,name=fee_related_changes,json=feeRelatedChanges,proto3" json:"fee_related_changes,omitempty"`
	TxRelatedChanges        uint32                 `protobuf:"varint,6,opt,name=tx_related_changes,json=txRelatedChanges,proto3" json:"tx_related_changes,omitempty"`
	OperationRelatedChanges uint32                 `protobuf:"varint,7,opt,name=operation_related_changes,json=operationRelatedChanges,proto3" json:"operation_related_changes,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LedgerChangeStats) Reset() {
	*x = LedgerChangeStats{}
	mi := &file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerChangeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerChangeStats) ProtoMessage() {}

func (x *LedgerChangeStats) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerChangeStats.ProtoReflect.Descriptor instead.
func (*LedgerChangeStats) Descriptor() ([]byte, []int) {
	return file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDescGZIP(), []int{0}
}

func (x *LedgerChangeStats) GetLedgerSequence() uint32 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *LedgerChangeStats) GetLedgerEntriesCreated() uint32 {
	if x != nil {
		return x.LedgerEntriesCreated
	}
	return 0
}

func (x *LedgerChangeStats) GetLedgerEntriesUpdated() uint32 {
	if x != nil {
		return x.LedgerEntriesUpdated
	}
	return 0
}

func (x *LedgerChangeStats) GetLedgerEntriesDeleted() uint32 {
	if x != nil {
		return x.LedgerEntriesDeleted
	}
	return 0
}

func (x *LedgerChangeStats) GetFeeRelatedChanges() uint32 {
	if x != nil {
		return x.FeeRelatedChanges
	}
	return 0
}

func (x *LedgerChangeStats) GetTxRelatedChanges() uint32 {
	if x != nil {
		return x.TxRelatedChanges
	}
	return 0
}

func (x *LedgerChangeStats) GetOperationRelatedChanges() uint32 {
	if x != nil {
		return x.OperationRelatedChanges
	}
	return 0
}

var File_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto protoreflect.FileDescriptor

const file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDesc = "" +
	"\n" +
	"Gexamples/processors/ledger-change-stats/proto/ledger_change_stats.proto\x12\x18nebu.ledger_change_stats\"\xf8\x02\n" +
	"\x11LedgerChangeStats\x12'\n" +
	"\x0fledger_sequence\x18\x01 \x01(\rR\x0eledgerSequence\x124\n" +
	"\x16ledger_entries_created\x18\x02 \x01(\rR\x14ledgerEntriesCreated\x124\n" +
	"\x16ledger_entries_updated\x18\x03 \x01(\rR\x14ledgerEntriesUpdated\x124\n" +
	"\x16ledger_entries_deleted\x18\x04 \x01(\rR\x14ledgerEntriesDeleted\x12.\n" +
	"\x13fee_related_changes\x18\x05 \x01(\rR\x11feeRelatedChanges\x12,\n" +
	"\x12tx_related_changes\x18\x06 \x01(\rR\x10txRelatedChanges\x12:\n" +
	"\x19operation_related_changes\x18\a \x01(\rR\x17operationRelatedChangesBXZVgithub.com/withObsrvr/nebu/examples/processors/ledger-change-stats/proto;changestatspbb\x06proto3"

var (
	file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDescOnce sync.Once
	file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDescData []byte
)

func file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDescGZIP() []byte {
	file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDescOnce.Do(func() {
		file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDesc), len(file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDesc)))
	})
	return file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDescData
}

var file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_goTypes = []any{
	(*LedgerChangeStats)(nil), // 0: nebu.ledger_change_stats.LedgerChangeStats
}
var file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_init() }
func file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_init() {
	if File_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDesc), len(file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_goTypes,
		DependencyIndexes: file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_depIdxs,
		MessageInfos:      file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_msgTypes,
	}.Build()
	File_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto = out.File
	file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_goTypes = nil
	file_examples_processors_ledger_change_stats_proto_ledger_change_stats_proto_depIdxs = nil
}
