// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: examples/processors/transaction-stats/proto/transaction_stats.proto

package txstatspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionStats struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	StartLedger            uint32                 `protobuf:"varint,1,opt,name=start_ledger,json=startLedger,proto3" json:"start_ledger,omitempty"`
	EndLedger              uint32                 `protobuf:"varint,2,opt,name=end_ledger,json=endLedger,proto3" json:"end_ledger,omitempty"`
	SuccessfulTransactions uint64                 `protobuf:"varint,3,opt,name=successful_transactions,json=successfulTransactions,proto3" json:"successful_transactions,omitempty"`
	FailedTransactions     uint64                 `protobuf:"varint,4,opt,name=failed_transactions,json=failedTransactions,proto3" json:"failed_transactions,omitempty"`
	TotalTransactions      uint64                 `protobuf:"varint,5,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	OperationsInSuccessful uint64                 `protobuf:"varint,6,opt,name=operations_in_successful,json=operationsInSuccessful,proto3" json:"operations_in_successful,omitempty"`
	OperationsInFailed     uint64                 `protobuf:"varint,7,opt,name=operations_in_failed,json=operationsInFailed,proto3" json:"operations_in_failed,omitempty"`
	TotalOperations        uint64                 `protobuf:"varint,8,opt,name=total_operations,json=totalOperations,proto3" json:"total_operations,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TransactionStats) Reset() {
	*x = TransactionStats{}
	mi := &file_examples_processors_transaction_stats_proto_transaction_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStats) ProtoMessage() {}

func (x *TransactionStats) ProtoReflect() protoreflect.Message {
	mi := &file_examples_processors_transaction_stats_proto_transaction_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStats.ProtoReflect.Descriptor instead.
func (*TransactionStats) Descriptor() ([]byte, []int) {
	return file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionStats) GetStartLedger() uint32 {
	if x != nil {
		return x.StartLedger
	}
	return 0
}

func (x *TransactionStats) GetEndLedger() uint32 {
	if x != nil {
		return x.EndLedger
	}
	return 0
}

func (x *TransactionStats) GetSuccessfulTransactions() uint64 {
	if x != nil {
		return x.SuccessfulTransactions
	}
	return 0
}

func (x *TransactionStats) GetFailedTransactions() uint64 {
	if x != nil {
		return x.FailedTransactions
	}
	return 0
}

func (x *TransactionStats) GetTotalTransactions() uint64 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *TransactionStats) GetOperationsInSuccessful() uint64 {
	if x != nil {
		return x.OperationsInSuccessful
	}
	return 0
}

func (x *TransactionStats) GetOperationsInFailed() uint64 {
	if x != nil {
		return x.OperationsInFailed
	}
	return 0
}

func (x *TransactionStats) GetTotalOperations() uint64 {
	if x != nil {
		return x.TotalOperations
	}
	return 0
}

var File_examples_processors_transaction_stats_proto_transaction_stats_proto protoreflect.FileDescriptor

const file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDesc = "" +
	"\n" +
	"Cexamples/processors/transaction-stats/proto/transaction_stats.proto\x12\x16nebu.transaction_stats\"\x84\x03\n" +
	"\x10TransactionStats\x12!\n" +
	"\fstart_ledger\x18\x01 \x01(\rR\vstartLedger\x12\x1d\n" +
	"\n" +
	"end_ledger\x18\x02 \x01(\rR\tendLedger\x127\n" +
	"\x17successful_transactions\x18\x03 \x01(\x04R\x16successfulTransactions\x12/\n" +
	"\x13failed_transactions\x18\x04 \x01(\x04R\x12failedTransactions\x12-\n" +
	"\x12total_transactions\x18\x05 \x01(\x04R\x11totalTransactions\x128\n" +
	"\x18operations_in_successful\x18\x06 \x01(\x04R\x16operationsInSuccessful\x120\n" +
	"\x14operations_in_failed\x18\a \x01(\x04R\x12operationsInFailed\x12)\n" +
	"\x10total_operations\x18\b \x01(\x04R\x0ftotalOperationsBRZPgithub.com/withObsrvr/nebu/examples/processors/transaction-stats/proto;txstatspbb\x06proto3"

var (
	file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDescOnce sync.Once
	file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDescData []byte
)

func file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDescGZIP() []byte {
	file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDescOnce.Do(func() {
		file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDesc), len(file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDesc)))
	})
	return file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDescData
}

var file_examples_processors_transaction_stats_proto_transaction_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_processors_transaction_stats_proto_transaction_stats_proto_goTypes = []any{
	(*TransactionStats)(nil), // 0: nebu.transaction_stats.TransactionStats
}
var file_examples_processors_transaction_stats_proto_transaction_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_processors_transaction_stats_proto_transaction_stats_proto_init() }
func file_examples_processors_transaction_stats_proto_transaction_stats_proto_init() {
	if File_examples_processors_transaction_stats_proto_transaction_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDesc), len(file_examples_processors_transaction_stats_proto_transaction_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_processors_transaction_stats_proto_transaction_stats_proto_goTypes,
		DependencyIndexes: file_examples_processors_transaction_stats_proto_transaction_stats_proto_depIdxs,
		MessageInfos:      file_examples_processors_transaction_stats_proto_transaction_stats_proto_msgTypes,
	}.Build()
	File_examples_processors_transaction_stats_proto_transaction_stats_proto = out.File
	file_examples_processors_transaction_stats_proto_transaction_stats_proto_goTypes = nil
	file_examples_processors_transaction_stats_proto_transaction_stats_proto_depIdxs = nil
}
