name: SBOM

on:
  push:
    branches:
      - main

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: SCF-Public-Goods-Maintenance/pg-atlas-sbom-action@0981ee36e88e3f973b01aa7f0ab9231116e4ab28
